apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  sa-password: "s0mePa$$wordL0Lz"
  connectionstring: "Data Source=octopetshop-sqlserver-cluster-ip-service;Initial Catalog=OctoPetShop; User ID=sa; Password=s0mePa$$wordL0Lz"